services:
  postgres-db:
    image: postgres:16
    container_name: gom_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gom}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-gom_db}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

  vault:
    image: hashicorp/vault
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/file
    command: server -dev -dev-root-token-id=${VAULT_DEV_ROOT_TOKEN_ID}

volumes:
  pg_data:
    driver: local
  vault_data:
    driver: local
