services:
  postgres-db:
    image: postgres:16
    container_name: gom_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gom}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-gom_db}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

volumes:
  pg_data:
    driver: local
